[RR] Made some minor changes in README
OpenLake/toothbrush pull request #20
Opened 2021-06-04 07:39 UTC by Ananyaiitbhilai

-Spelling of applications was corrected
-made changes in documentation instructions

2021-06-04 07:42 UTC, Ananyaiitbhilai commented
@yatendra1999

2021-06-04 15:35 UTC, yatendra1999 commented
Don't make new PRs for the same topic.

2021-06-04 15:38 UTC, yatendra1999 requested changes

2021-06-04 15:38 UTC, yatendra1999 commented on README.md
> +```
Put all three into a single code block like 
```
c1
c2
```

2021-06-04 15:45 UTC, Ananyaiitbhilai commented on README.md
> +```
Ok done.

2021-06-04 15:48 UTC, Ananyaiitbhilai commented
Pls review now...I made the asked changes

2021-06-04 15:48 UTC, Ananyaiitbhilai commented
> Don't make new PRs for the same topic.

Okk...sorry

2021-06-05 06:27 UTC, Ananyaiitbhilai commented
@yatendra1999

2021-06-05 07:51 UTC, yatendra1999 approved these changes

2021-06-05 07:51 UTC, merged